[2021-05-17 09:13:46,173] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: matches_links.get_autumn_nations_cup_links 2021-04-24T10:00:00+00:00 [queued]>
[2021-05-17 09:13:46,177] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: matches_links.get_autumn_nations_cup_links 2021-04-24T10:00:00+00:00 [queued]>
[2021-05-17 09:13:46,177] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-17 09:13:46,177] {taskinstance.py:1069} INFO - Starting attempt 3 of 4
[2021-05-17 09:13:46,177] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-17 09:13:46,182] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): get_autumn_nations_cup_links> on 2021-04-24T10:00:00+00:00
[2021-05-17 09:13:46,184] {standard_task_runner.py:52} INFO - Started process 11166 to run task
[2021-05-17 09:13:46,191] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'matches_links', 'get_autumn_nations_cup_links', '2021-04-24T10:00:00+00:00', '--job-id', '10', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/matches_links/matches_links.py', '--cfg-path', '/var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T/tmpkh3utz27', '--error-file', '/var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T/tmpxjmao_ug']
[2021-05-17 09:13:46,193] {standard_task_runner.py:77} INFO - Job 10: Subtask get_autumn_nations_cup_links
[2021-05-17 09:13:46,220] {logging_mixin.py:104} INFO - Running <TaskInstance: matches_links.get_autumn_nations_cup_links 2021-04-24T10:00:00+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2021-05-17 09:13:46,241] {taskinstance.py:1281} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=matches_links
AIRFLOW_CTX_TASK_ID=get_autumn_nations_cup_links
AIRFLOW_CTX_EXECUTION_DATE=2021-04-24T10:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=backfill__2021-04-24T10:00:00+00:00
[2021-05-17 09:13:46,241] {bash.py:135} INFO - Tmp dir root location: 
 /var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T
[2021-05-17 09:13:46,242] {bash.py:158} INFO - Running command: Rscript /Users/harry/rugby_data_project_airflow/R/scripts/create_matches_table.R  https://www.rugbypass.com/autumn-nations-cup/matches/
[2021-05-17 09:13:46,248] {bash.py:169} INFO - Output:
[2021-05-17 09:13:47,417] {bash.py:173} INFO - ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──
[2021-05-17 09:13:47,422] {bash.py:173} INFO - ✔ ggplot2 3.3.3     ✔ purrr   0.3.3
[2021-05-17 09:13:47,422] {bash.py:173} INFO - ✔ tibble  3.0.4     ✔ dplyr   1.0.2
[2021-05-17 09:13:47,423] {bash.py:173} INFO - ✔ tidyr   1.1.2     ✔ stringr 1.4.0
[2021-05-17 09:13:47,423] {bash.py:173} INFO - ✔ readr   1.3.1     ✔ forcats 0.5.0
[2021-05-17 09:13:47,498] {bash.py:173} INFO - ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
[2021-05-17 09:13:47,498] {bash.py:173} INFO - ✖ dplyr::filter() masks stats::filter()
[2021-05-17 09:13:47,498] {bash.py:173} INFO - ✖ dplyr::lag()    masks stats::lag()
[2021-05-17 09:13:47,508] {bash.py:173} INFO - 
[2021-05-17 09:13:47,509] {bash.py:173} INFO - Attaching package: ‘lubridate’
[2021-05-17 09:13:47,509] {bash.py:173} INFO - 
[2021-05-17 09:13:47,509] {bash.py:173} INFO - The following objects are masked from ‘package:base’:
[2021-05-17 09:13:47,509] {bash.py:173} INFO - 
[2021-05-17 09:13:47,510] {bash.py:173} INFO -     date, intersect, setdiff, union
[2021-05-17 09:13:47,510] {bash.py:173} INFO - 
[2021-05-17 09:13:47,511] {bash.py:173} INFO - Loading required package: xml2
[2021-05-17 09:13:47,520] {bash.py:173} INFO - 
[2021-05-17 09:13:47,520] {bash.py:173} INFO - Attaching package: ‘rvest’
[2021-05-17 09:13:47,521] {bash.py:173} INFO - 
[2021-05-17 09:13:47,521] {bash.py:173} INFO - The following object is masked from ‘package:purrr’:
[2021-05-17 09:13:47,521] {bash.py:173} INFO - 
[2021-05-17 09:13:47,522] {bash.py:173} INFO -     pluck
[2021-05-17 09:13:47,522] {bash.py:173} INFO - 
[2021-05-17 09:13:47,522] {bash.py:173} INFO - The following object is masked from ‘package:readr’:
[2021-05-17 09:13:47,522] {bash.py:173} INFO - 
[2021-05-17 09:13:47,523] {bash.py:173} INFO -     guess_encoding
[2021-05-17 09:13:47,523] {bash.py:173} INFO - 
[2021-05-17 09:13:47,527] {bash.py:173} INFO - [1] "Getting autumn_nations_cup links"
[2021-05-17 09:13:49,730] {bash.py:173} INFO - [1] "autumn_nations_cup saved"
[2021-05-17 09:13:49,745] {bash.py:177} INFO - Command exited with return code 0
[2021-05-17 09:13:49,757] {taskinstance.py:1185} INFO - Marking task as SUCCESS. dag_id=matches_links, task_id=get_autumn_nations_cup_links, execution_date=20210424T100000, start_date=20210517T081346, end_date=20210517T081349
[2021-05-17 09:13:49,768] {taskinstance.py:1246} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-05-17 09:13:49,789] {local_task_job.py:146} INFO - Task exited with return code 0
[2021-05-17 09:27:13,599] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: matches_links.get_autumn_nations_cup_links 2021-04-24T10:00:00+00:00 [queued]>
[2021-05-17 09:27:13,603] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: matches_links.get_autumn_nations_cup_links 2021-04-24T10:00:00+00:00 [queued]>
[2021-05-17 09:27:13,603] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-17 09:27:13,604] {taskinstance.py:1069} INFO - Starting attempt 3 of 3
[2021-05-17 09:27:13,604] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-17 09:27:13,608] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): get_autumn_nations_cup_links> on 2021-04-24T10:00:00+00:00
[2021-05-17 09:27:13,610] {standard_task_runner.py:52} INFO - Started process 20209 to run task
[2021-05-17 09:27:13,618] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'matches_links', 'get_autumn_nations_cup_links', '2021-04-24T10:00:00+00:00', '--job-id', '6', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/matches_links/matches_links.py', '--cfg-path', '/var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T/tmpf7oq9e3w', '--error-file', '/var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T/tmpzkz0p4cz']
[2021-05-17 09:27:13,620] {standard_task_runner.py:77} INFO - Job 6: Subtask get_autumn_nations_cup_links
[2021-05-17 09:27:13,654] {logging_mixin.py:104} INFO - Running <TaskInstance: matches_links.get_autumn_nations_cup_links 2021-04-24T10:00:00+00:00 [running]> on host Henrys-MacBook-Pro.local
[2021-05-17 09:27:13,680] {taskinstance.py:1281} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=matches_links
AIRFLOW_CTX_TASK_ID=get_autumn_nations_cup_links
AIRFLOW_CTX_EXECUTION_DATE=2021-04-24T10:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=backfill__2021-04-24T10:00:00+00:00
[2021-05-17 09:27:13,681] {bash.py:135} INFO - Tmp dir root location: 
 /var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T
[2021-05-17 09:27:13,682] {bash.py:158} INFO - Running command: Rscript /Users/harry/rugby_data_project_airflow/R/scripts/create_matches_table.R  https://www.rugbypass.com/autumn-nations-cup/matches/ 2021-04-24
[2021-05-17 09:27:13,691] {bash.py:169} INFO - Output:
[2021-05-17 09:27:14,868] {bash.py:173} INFO - ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──
[2021-05-17 09:27:14,873] {bash.py:173} INFO - ✔ ggplot2 3.3.3     ✔ purrr   0.3.3
[2021-05-17 09:27:14,873] {bash.py:173} INFO - ✔ tibble  3.0.4     ✔ dplyr   1.0.2
[2021-05-17 09:27:14,873] {bash.py:173} INFO - ✔ tidyr   1.1.2     ✔ stringr 1.4.0
[2021-05-17 09:27:14,873] {bash.py:173} INFO - ✔ readr   1.3.1     ✔ forcats 0.5.0
[2021-05-17 09:27:14,946] {bash.py:173} INFO - ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
[2021-05-17 09:27:14,946] {bash.py:173} INFO - ✖ dplyr::filter() masks stats::filter()
[2021-05-17 09:27:14,946] {bash.py:173} INFO - ✖ dplyr::lag()    masks stats::lag()
[2021-05-17 09:27:14,956] {bash.py:173} INFO - 
[2021-05-17 09:27:14,956] {bash.py:173} INFO - Attaching package: ‘lubridate’
[2021-05-17 09:27:14,956] {bash.py:173} INFO - 
[2021-05-17 09:27:14,956] {bash.py:173} INFO - The following objects are masked from ‘package:base’:
[2021-05-17 09:27:14,957] {bash.py:173} INFO - 
[2021-05-17 09:27:14,957] {bash.py:173} INFO -     date, intersect, setdiff, union
[2021-05-17 09:27:14,957] {bash.py:173} INFO - 
[2021-05-17 09:27:14,958] {bash.py:173} INFO - Loading required package: xml2
[2021-05-17 09:27:14,965] {bash.py:173} INFO - 
[2021-05-17 09:27:14,965] {bash.py:173} INFO - Attaching package: ‘rvest’
[2021-05-17 09:27:14,966] {bash.py:173} INFO - 
[2021-05-17 09:27:14,966] {bash.py:173} INFO - The following object is masked from ‘package:purrr’:
[2021-05-17 09:27:14,966] {bash.py:173} INFO - 
[2021-05-17 09:27:14,967] {bash.py:173} INFO -     pluck
[2021-05-17 09:27:14,967] {bash.py:173} INFO - 
[2021-05-17 09:27:14,967] {bash.py:173} INFO - The following object is masked from ‘package:readr’:
[2021-05-17 09:27:14,967] {bash.py:173} INFO - 
[2021-05-17 09:27:14,968] {bash.py:173} INFO -     guess_encoding
[2021-05-17 09:27:14,968] {bash.py:173} INFO - 
[2021-05-17 09:27:14,969] {bash.py:173} INFO - Warning message:
[2021-05-17 09:27:14,970] {bash.py:173} INFO - All formats failed to parse. No formats found.
[2021-05-17 09:27:14,977] {bash.py:173} INFO - [1] "Getting autumn_nations_cup links"
[2021-05-17 09:27:17,191] {bash.py:173} INFO - Error: Can't combine `date` <character> and `date` <date>.
[2021-05-17 09:27:17,200] {bash.py:173} INFO - Backtrace:
[2021-05-17 09:27:17,200] {bash.py:173} INFO -      █
[2021-05-17 09:27:17,201] {bash.py:173} INFO -   1. ├─`%>%`(...)
[2021-05-17 09:27:17,201] {bash.py:173} INFO -   2. ├─readr::write_csv(., csv_file)
[2021-05-17 09:27:17,202] {bash.py:173} INFO -   3. │ └─readr::write_delim(...)
[2021-05-17 09:27:17,202] {bash.py:173} INFO -   4. │   ├─base::stopifnot(is.data.frame(x))
[2021-05-17 09:27:17,202] {bash.py:173} INFO -   5. │   └─base::is.data.frame(x)
[2021-05-17 09:27:17,203] {bash.py:173} INFO -   6. ├─dplyr::distinct(., rugby_pass_url, .keep_all = TRUE)
[2021-05-17 09:27:17,203] {bash.py:173} INFO -   7. └─dplyr::bind_rows(., table)
[2021-05-17 09:27:17,203] {bash.py:173} INFO -   8.   └─vctrs::vec_rbind(!!!dots, .names_to = .id)
[2021-05-17 09:27:17,203] {bash.py:173} INFO -   9.     └─(function () ...
[2021-05-17 09:27:17,204] {bash.py:173} INFO -  10.       └─vctrs::vec_default_ptype2(...)
[2021-05-17 09:27:17,204] {bash.py:173} INFO -  11.         └─vctrs:::vec_ptype2_df_fallback(x, y, opts)
[2021-05-17 09:27:17,204] {bash.py:173} INFO -  12.           └─vctrs:::vec_ptype2_params(...)
[2021-05-17 09:27:17,205] {bash.py:173} INFO -  13.             └─vctrs:::vec_ptype2_opts(x, y, opts = opts, x_arg = x_arg, y_arg = y_arg)
[2021-05-17 09:27:17,205] {bash.py:173} INFO -  14.               └─(function () ...
[2021-05-17 09:27:17,206] {bash.py:173} INFO -  15.                 └─vctrs::vec_default_ptype2(...)
[2021-05-17 09:27:17,206] {bash.py:173} INFO -  16.                   └─vctrs::stop_incompatible_type(...)
[2021-05-17 09:27:17,206] {bash.py:173} INFO -  17.                     └─vctrs:::stop_incompatible(...)
[2021-05-17 09:27:17,207] {bash.py:173} INFO -  18.                       └─vctrs:::stop_vctrs(...)
[2021-05-17 09:27:17,207] {bash.py:173} INFO - Execution halted
[2021-05-17 09:27:17,220] {bash.py:177} INFO - Command exited with return code 1
[2021-05-17 09:27:17,226] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-05-17 09:27:17,229] {taskinstance.py:1525} INFO - Marking task as FAILED. dag_id=matches_links, task_id=get_autumn_nations_cup_links, execution_date=20210424T100000, start_date=20210517T082713, end_date=20210517T082717
[2021-05-17 09:27:17,272] {local_task_job.py:146} INFO - Task exited with return code 1
