[2021-05-16 09:42:01,244] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: airflow_tutorial_v01.sleep 2017-08-11T17:00:00+00:00 [queued]>
[2021-05-16 09:42:01,255] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: airflow_tutorial_v01.sleep 2017-08-11T17:00:00+00:00 [queued]>
[2021-05-16 09:42:01,255] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-16 09:42:01,255] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-05-16 09:42:01,255] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-16 09:42:01,266] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): sleep> on 2017-08-11T17:00:00+00:00
[2021-05-16 09:42:01,269] {standard_task_runner.py:52} INFO - Started process 58840 to run task
[2021-05-16 09:42:01,280] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'airflow_tutorial_v01', 'sleep', '2017-08-11T17:00:00+00:00', '--job-id', '5178', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Untitled.py', '--cfg-path', '/var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T/tmpqp8cmdmp', '--error-file', '/var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T/tmpiipzj9nd']
[2021-05-16 09:42:01,283] {standard_task_runner.py:77} INFO - Job 5178: Subtask sleep
[2021-05-16 09:42:01,343] {logging_mixin.py:104} INFO - Running <TaskInstance: airflow_tutorial_v01.sleep 2017-08-11T17:00:00+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2021-05-16 09:42:01,388] {taskinstance.py:1281} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=airflow_tutorial_v01
AIRFLOW_CTX_TASK_ID=sleep
AIRFLOW_CTX_EXECUTION_DATE=2017-08-11T17:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2017-08-11T17:00:00+00:00
[2021-05-16 09:42:01,389] {bash.py:135} INFO - Tmp dir root location: 
 /var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T
[2021-05-16 09:42:01,391] {bash.py:158} INFO - Running command: sleep 5
[2021-05-16 09:42:01,404] {bash.py:169} INFO - Output:
[2021-05-16 09:42:06,322] {local_task_job.py:174} WARNING - The recorded hostname henrys-macbook-pro.local does not match this instance's hostname 1.0.0.127.in-addr.arpa
[2021-05-16 09:42:06,335] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 58840
[2021-05-16 09:42:06,336] {taskinstance.py:1265} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-05-16 09:42:06,336] {bash.py:185} INFO - Sending SIGTERM signal to bash process group
[2021-05-16 09:42:06,344] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/operators/bash.py", line 171, in execute
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1267, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-05-16 09:42:06,348] {taskinstance.py:1525} INFO - Marking task as UP_FOR_RETRY. dag_id=airflow_tutorial_v01, task_id=sleep, execution_date=20170811T170000, start_date=20210516T084201, end_date=20210516T084206
[2021-05-16 09:42:06,368] {process_utils.py:66} INFO - Process psutil.Process(pid=58840, status='terminated', exitcode=1, started='09:42:01') (58840) terminated with exit code 1
[2021-05-16 09:42:06,369] {process_utils.py:66} INFO - Process psutil.Process(pid=58841, status='terminated', started='09:42:01') (58841) terminated with exit code None
